import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  heroSection: {
    width: "100%",
    height: 340,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    overflow: "hidden",
    position: "relative",
  },
  heroImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  backButton: {
    position: "absolute",
    top: 52,
    left: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(27,30,40,0.16)",
    justifyContent: "center",
    alignItems: "center",
  },
  content: {
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    backgroundColor: "#fff",
    marginTop: -40,
    paddingHorizontal: 20,
    paddingTop: 20,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: -4 },
    shadowRadius: 12,
    elevation: 2,
  },
  handle: {
    width: 36,
    height: 5,
    borderRadius: 16,
    backgroundColor: "#7D848D",
    opacity: 0.2,
    alignSelf: "center",
    marginBottom: 24,
  },
  header: {
    marginBottom: 16,
  },
  bookedBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#FFF4E5",
    borderColor: "#FFB74D",
    borderWidth: 1,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    marginBottom: 16,
  },
  bookedBannerEmoji: {
    fontSize: 18,
  },
  bookedBannerText: {
    color: "#D35400",
    fontSize: 15,
    fontWeight: "700",
  },
  title: {
    color: "#1B1E28",
    fontSize: 22,
    fontWeight: "700",
    marginBottom: 4,
  },
  duration: {
    color: "#7D848D",
    fontSize: 14,
  },
  meta: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: 20,
    rowGap: 10,
  },
  priceRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: 20,
  },
  metaItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  metaText: {
    color: "#7D848D",
    fontSize: 14,
  },
  rating: {
    color: "#1B1E28",
    fontSize: 14,
    fontWeight: "500",
    marginLeft: 4,
  },
  reviews: {
    color: "#7D848D",
    fontSize: 14,
  },
  price: {
    color: "#15C4C8",
    fontSize: 14,
    fontWeight: "600",
  },
  priceUnit: {
    color: "#7D848D",
    fontSize: 14,
  },
  gallery: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 24,
  },
  galleryImage: {
    width: 100,
    height: 100,
    borderRadius: 16,
  },
  sectionTitle: {
    color: "#1B1E28",
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 8,
  },
  descriptionContent: {
    color: "#3A3A3A",
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 20,
    fontWeight: "400",
  },
  description: {
    color: "#7D848D",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
  },
  readMore: {
    color: "#15C4C8",
    textDecorationLine: "underline",
  },
  bookingSection: {
    marginBottom: 16,
  },
  quantitySelector: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 20,
    marginTop: 8,
  },
  quantityButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#0F93C3",
    justifyContent: "center",
    alignItems: "center",
  },
  quantityButtonText: {
    color: "#fff",
    fontSize: 24,
    fontWeight: "600",
  },
  quantityText: {
    fontSize: 20,
    fontWeight: "600",
    color: "#1B1E28",
    minWidth: 40,
    textAlign: "center",
  },
  reviewsContainer: {
    marginTop: 12,
  },
  bookButton: {
    width: "100%",
    height: 54,
    borderRadius: 16,
    backgroundColor: "#0F93C3",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 24,
  },
  bookButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
});
