import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  heroSection: {
    width: "100%",
    height: 340,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    overflow: "hidden",
    position: "relative",
  },
  heroImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  backButton: {
    position: "absolute",
    top: 52,
    left: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(27,30,40,0.16)",
    justifyContent: "center",
    alignItems: "center",
  },
  content: {
    flex: 1,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    backgroundColor: "#fff",
    marginTop: -40,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: -4 },
    shadowRadius: 12,
    elevation: 2,
  },
  scrollContainer: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 40,
  },
  handle: {
    width: 36,
    height: 5,
    borderRadius: 16,
    backgroundColor: "#7D848D",
    opacity: 0.2,
    alignSelf: "center",
    marginBottom: 24,
  },
  header: {
    marginBottom: 16,
  },
  title: {
    color: "#1B1E28",
    fontSize: 22,
    fontWeight: "700",
    marginBottom: 4,
  },
  address: {
    color: "#7D848D",
    fontSize: 14,
  },
  meta: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: 20,
    rowGap: 10,
  },
  metaItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  metaText: {
    color: "#7D848D",
    fontSize: 14,
  },
  rating: {
    color: "#1B1E28",
    fontSize: 14,
    fontWeight: "500",
    marginLeft: 4,
  },
  reviews: {
    color: "#7D848D",
    fontSize: 14,
  },
  price: {
    color: "#15C4C8",
    fontSize: 14,
    fontWeight: "600",
  },
  priceUnit: {
    color: "#7D848D",
    fontSize: 14,
  },
  contactSection: {
    backgroundColor: "#F5F7FA",
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    gap: 12,
  },
  contactItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  contactText: {
    color: "#1B1E28",
    fontSize: 14,
    flex: 1,
  },
  gallery: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 24,
  },
  galleryImage: {
    width: 100,
    height: 100,
    borderRadius: 16,
    marginRight: 12,
  },
  sectionTitle: {
    color: "#1B1E28",
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 12,
  },
  description: {
    color: "#7D848D",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
  },
  readMore: {
    color: "#15C4C8",
    textDecorationLine: "underline",
  },
  roomTypesContainer: {
    gap: 12,
    marginBottom: 24,
  },
  roomTypeCard: {
    backgroundColor: "#F5F7FA",
    borderRadius: 16,
    padding: 16,
    borderWidth: 2,
    borderColor: "#E8ECF0",
    position: "relative",
    marginBottom: 10,
  },
  roomTypeCardSelected: {
    backgroundColor: "#E6F7F8",
    borderColor: "#0F93C3",
    borderWidth: 2,
  },
  roomTypeHeader: {
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  roomTypeName: {
    color: "#1B1E28",
    fontSize: 16,
    fontWeight: "600",
  },
  roomTypeNameSelected: {
    color: "#0F93C3",
  },
  roomTypePrice: {
    color: "#15C4C8",
    fontSize: 16,
    fontWeight: "600",
  },
  roomTypePriceSelected: {
    color: "#0F93C3",
  },
  roomTypeCapacity: {
    color: "#7D848D",
    fontSize: 14,
    marginBottom: 4,
  },
  roomTypeAmenities: {
    color: "#7D848D",
    fontSize: 13,
    lineHeight: 18,
  },
  roomTypeAvailability: {
    color: "#0F93C3",
    fontSize: 14,
    fontWeight: "600",
    marginTop: 6,
  },
  selectedIndicator: {
    position: "absolute",
    top: 12,
    right: 12,
  },
  bookingSection: {
    marginBottom: 16,
  },
  quantitySelector: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 20,
    marginTop: 8,
  },
  quantityButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#0F93C3",
    justifyContent: "center",
    alignItems: "center",
  },
  quantityButtonText: {
    color: "#fff",
    fontSize: 24,
    fontWeight: "600",
  },
  quantityText: {
    fontSize: 20,
    fontWeight: "600",
    color: "#1B1E28",
    minWidth: 40,
    textAlign: "center",
  },
  reviewsContainer: {
    marginTop: 12,
  },
  bookButton: {
    width: "100%",
    height: 54,
    borderRadius: 16,
    backgroundColor: "#0F93C3",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 24,
  },
  bookButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
});
