import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  page: {
    minHeight: "100%",
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 32,
    paddingHorizontal: 16,
    backgroundColor: "#eff4f9",
  },
  frame: {
    width: 375,
    maxWidth: "100%",
    minHeight: 600,
    backgroundColor: "#fff",
    borderRadius: 30,
    shadowColor: "#152242",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 8,
    overflow: "hidden",
    position: "relative",
  },
  body: {
    paddingTop: 60,
    paddingHorizontal: 24,
    paddingBottom: 40,
    gap: 24,
    width: "100%",
    alignItems: "center",
  },
  iconContainer: {
    width: 120,
    height: 120,
    borderRadius: 60,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  successIcon: {
    backgroundColor: "#e8f5e9",
  },
  failureIcon: {
    backgroundColor: "#ffebee",
  },
  iconText: {
    fontSize: 64,
  },
  header: {
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
    width: "100%",
  },
  title: {
    fontSize: 26,
    fontWeight: "700",
    color: "#000",
    textAlign: "center",
  },
  successTitle: {
    color: "#2e7d32",
  },
  failureTitle: {
    color: "#c62828",
  },
  subtitle: {
    fontSize: 15,
    color: "#7d848d",
    textAlign: "center",
    lineHeight: 22,
  },
  detailsCard: {
    width: "100%",
    backgroundColor: "#f7f7f9",
    borderRadius: 16,
    padding: 20,
    gap: 16,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  detailLabel: {
    fontSize: 14,
    color: "#7d848d",
    flex: 1,
  },
  detailValue: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1b1e28",
    flex: 2,
    textAlign: "right",
  },
  detailValueHighlight: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0f93c3",
  },
  divider: {
    height: 1,
    backgroundColor: "#e0e0e0",
    marginVertical: 4,
  },
  buttonsContainer: {
    width: "100%",
    gap: 12,
    marginTop: 8,
  },
  primaryButton: {
    width: "100%",
    height: 56,
    borderRadius: 16,
    backgroundColor: "#0f93c3",
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  secondaryButton: {
    width: "100%",
    height: 56,
    borderRadius: 16,
    backgroundColor: "#f7f7f9",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  secondaryButtonText: {
    color: "#1b1e28",
    fontSize: 16,
    fontWeight: "600",
  },
  messageContainer: {
    width: "100%",
    backgroundColor: "#fff3e0",
    borderRadius: 12,
    padding: 16,
    borderLeftWidth: 4,
    borderLeftColor: "#ff9800",
  },
  messageText: {
    fontSize: 13,
    color: "#e65100",
    lineHeight: 20,
  },
});
